### ISSUE TITLE
Grpc update breaks with Bazel 3.4.0 in docker container

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#11756]
Error log:
https://buildkite.com/bazel/google-bazel-presubmit/builds/36688#7500893b-351a-4549-86ae-19803c73cbd1

**Comment by katre** [comment]
Looks like something changed so bazel frontend is unable to communicate with the server inside the docker container for RBE autoconfig.

**Comment by keith** [comment]
We see this too with our projects and RBE and 3.4.0:

```

Starting local Bazel server and connecting to it...
--
  | ... still trying to connect to local Bazel server after 10 seconds ...
  | ... still trying to connect to local Bazel server after 20 seconds ...
  | ... still trying to connect to local Bazel server after 30 seconds ...
  | ... still trying to connect to local Bazel server after 40 seconds ...
  | ... still trying to connect to local Bazel server after 50 seconds ...
  | ... still trying to connect to local Bazel server after 60 seconds ...
  | ... still trying to connect to local Bazel server after 70 seconds ...
  | ... still trying to connect to local Bazel server after 80 seconds ...
  | ... still trying to connect to local Bazel server after 90 seconds ...
  | ... still trying to connect to local Bazel server after 100 seconds ...
  | ... still trying to connect to local Bazel server after 110 seconds ...
  | FATAL: couldn't connect to server (2502) after 120 seconds.

```

**Comment by katre** [comment]
Yes, we're trying to diagnose and get out a patch as fast as we can.

**Comment by nathanhleung** [comment]
Same issue here in a Docker runner on CircleCI:

```yml
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: medium+
```

```
Extracting Bazel installation...
 
Starting local Bazel server and connecting to it...
 
... still trying to connect to local Bazel server after 10 seconds ...
 
... still trying to connect to local Bazel server after 20 seconds ...
 
... still trying to connect to local Bazel server after 30 seconds ...
 
... still trying to connect to local Bazel server after 40 seconds ...
 
... still trying to connect to local Bazel server after 50 seconds ...
 
... still trying to connect to local Bazel server after 60 seconds ...
 
... still trying to connect to local Bazel server after 70 seconds ...
 
... still trying to connect to local Bazel server after 80 seconds ...
 
... still trying to connect to local Bazel server after 90 seconds ...
 
... still trying to connect to local Bazel server after 100 seconds ...
 
... still trying to connect to local Bazel server after 110 seconds ...
 
FATAL: couldn't connect to server (1521) after 120 seconds.
 
Makefile:5: recipe for target 'build' failed
 
make: *** [build] Error 37
 ```

**Comment by philwo** [comment]
@nathanhleung Can you confirm that in your case no remote execution is involved and this happens just when running Bazel 3.4.0 inside the Docker container on CircleCI?

**Comment by meisterT** [comment]
Repro without RBE:
```
docker run --rm -i -t l.gcr.io/google/rbe-ubuntu16-04@sha256:5464e3e83dc656fc6e4eae6a01f5c2645f1f7e95854b3802b85e86484132d90e bash

# wget https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64
# chmod +x bazelisk-linux-amd64
# touch WORKSPACE
# ./bazelisk-linux-amd64 info
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
... still trying to connect to local Bazel server after 30 seconds ...
... still trying to connect to local Bazel server after 40 seconds ...
... still trying to connect to local Bazel server after 50 seconds ...
... still trying to connect to local Bazel server after 60 seconds ...
... still trying to connect to local Bazel server after 70 seconds ...
```

**Comment by meisterT** [comment]
culprit seems to be https://github.com/bazelbuild/bazel/commit/dfbf87c9196a15d491e9cbb81ee2d3da416cc0c2

**Comment by nathanhleung** [comment]
> @nathanhleung Can you confirm that in your case no remote execution or `rbe_autoconfig` stuff is involved and this happens just when running Bazel 3.4.0 inside the Docker container on CircleCI?

Not sure how to confirm, but this is our Bazel install step:

```yml
install_bazel:
    # From https://docs.bazel.build/versions/master/install-ubuntu.html
    steps:
      - run: |
          sudo apt install curl gnupg apt-transport-https
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt \
            stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - run: sudo apt-get update && sudo apt-get -y install bazel
```

`.bazelrc` generated by this script:

```sh
#!/bin/bash

# Exit on error
set -e

echo "# Generated by ./scripts/generate_bazelrc.sh" > .bazelrc
echo "build --remote_cache=https://$BAZEL_CACHE_USER:$BAZEL_CACHE_PASSWORD@cache.company.xyz" >> .bazelrc
```

(nothing else)

And build command:

`bazel build //src/server_bin_deploy.jar`
