### ISSUE TITLE
bazel builds using gcr.io/cloud-builders/bazel failing with null pointer exception.

### ISSUE THREAD

**Issue by hildrum** [bazelbuild/bazel#6182]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel builds using gcr.io/cloud-builders/bazel failing with null pointer exception.

````
Step #3: Caused by: java.lang.NullPointerException
Step #3: 	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:560)
Step #3: 	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:319)
Step #3: 	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:396)
````

[Full stack trace](https://gist.github.com/hildrum/79ba0ad703129b63d5a7514bc77d2798)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`gcloud builds submit --config=config.yaml --no-source`
where config.yaml is:
````
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--recursive', 'https://bazel.googlesource.com/bazel']
  dir: '/workspace/'
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', 'https://bazel.googlesource.com/bazel', '4d8aaf9c6c1bbd485e520b8ff56d3489d093b300']
  dir: '/workspace/bazel'
- name: 'gcr.io/cloud-builders/git'
  args: ['reset', '--hard', '4d8aaf9c6c1bbd485e520b8ff56d3489d093b300']
  dir: '/workspace/bazel'
- name: 'gcr.io/cloud-builders/bazel'
  args: ['-c', 'bazel --host_jvm_args=-Dbazel.DigestFunction=SHA256 build --auth_enabled --tls_enabled --verbose_failures --keep_going -- ... -//kythe/... || 
true']
  dir: '/workspace/bazel'
  entrypoint: 'bash'
````

### What operating system are you running Bazel on?

Running via cloud build, so Ubunto

### What's the output of `bazel info release`?

That's not easy to run the way I'm running this.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

That's not easy to get the way I'm running this.

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

Problem started between Sept. 16th 2pm and Sept. 17th 2pm.  My bazel builds of tensorflow are also failing at the same point: ([tensorflow config file](https://gist.github.com/hildrum/a8dc3e71dcb77790b1eca76f90ad74fc)).  

My builds of kubernetes (configured the same way, with [kubernetes config file](https://gist.github.com/hildrum/4353ec706b358eba5938ace295fe2d4b)) are successful.
